site_name: Apischema
repo_name: wyfo/apischema
repo_url: https://github.com/wyfo/apischema

theme:
  name: material
  palette:
    scheme: preference
    primary: green
    accent: indigo

nav:
- Overview: index.md
- data_model.md
- "(De)serialization": de_serialization.md
- JSON schema: json_schema.md
- validation.md
- Conversions – (de)serialization customization: conversions.md
- configuration_management.md
- Examples:
  - OpenRPC: examples/open_rpc.md
  - SQLAlchemy support: examples/sqlalchemy.md
  - examples/pydantic_compatibility.md
  - examples/recoverable_fields.md
- benchmark.md
- Releases: https://github.com/wyfo/apischema/releases


markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: examples
- toc:
    permalink: True
#    toc_depth: 3
- admonition
- codehilite
- extra
- attr_list

plugins:
- search
- exclude:
    glob:
    - requirements.txt

